name: pyrite
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - huggingface_hub
  - wandb
  - timm
  - diffusers
  - accelerate
  - threadpoolctl
  - plotly
  - dill
  - einops
  - hydra-core
  - ipykernel
  - ipython
  - matplotlib
  - omegaconf
  - opencv
  - pandas
  - pyyaml
  - scipy
  - tqdm
  - zarr=2.18
  - spatialmath-python
  - numcodecs
  - scikit-video
  - scikit-fda
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  - eigen=3.4
  - cmake
  - pybind11
  - boost
  - fmt
  - spdlog
  - imageio-ffmpeg
  - nbformat
  - cvxpy