defaults:
  - _self_
  - task: online_correction_tf_single_arm.yaml

name: online_residual_tf

output_dir: ${oc.env:PYRITE_CHECKPOINT_FOLDERS}
_target_: diffusion_policy.workspace.train_online_residual_tf_workspace.TrainOnlineResidualTFWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.22_04.27.42_stow_new_blade_stow/checkpoints/latest.ckpt"


obs_encoder:    
  _target_: diffusion_policy.model.vision.timm_obs_encoder_force_residual.TimmObsEncoderForceResidual
  shape_meta: ${shape_meta}
  fuse_mode: modality-attention
  reduce_pretrained_lr: True

  ##### from scratch #####
  # model_name: 'vit_base_patch16_224'
  # model_name: 'resnet34'
  # model_name: 'vit_tiny_patch16_224'
  # model_name: 'efficientnet_b0'
  # model_name: 'efficientnet_b3'
  # pretrained: False
  # frozen: False

  vision_encoder_cfg:   # TODO: load this from base policy
    ##### from scratch #####
    # model_name: 'resnet34.a1_in1k'
    model_name: 'vit_base_patch32_clip_224.openai'
    # model_name: 'convnext_base.clip_laion2b_augreg_ft_in12k'
    pretrained: True
    frozen: True
    global_pool: ''

    # 'avg' or 'max' or 'soft_attention' or 'spatial_embedding' or 'transformer' or 'attention_pool_2d'
    feature_aggregation: 'attention_pool_2d'
    # feature_aggregation: null
    position_encoding: null

    # it only works for resnet. 32 (7x7) or 16 (14x14)
    downsample_ratio: 32

    transforms:
      - type: RandomCrop
        ratio: 0.95
      # RandomRotation is not compatible with BF16
      # - _target_: torchvision.transforms.RandomRotation
      #   degrees:
      #     - -5.0
      #     - 5.0
      #   expand: false
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.4
        saturation: 0.5
        hue: 0.08
      # - _target_: torchvision.transforms.RandomPerspective
      #   distortion_scale: 0.5
      #   p: 1.0
      # - _target_: torchvision.transforms.ElasticTransform
      #   alpha: 50.0
      #   sigma: 5.0
      # - _target_: torchvision.transforms.RandomPerspective
      #   distortion_scale: 0.5
      #   p: 1.0
      # - _target_: torchvision.transforms.ElasticTransform
      #   alpha: 50.0
      #   sigma: 5.0
      # - _target_: torchvision.transforms.RandomCrop
      #   size: 192

    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True
  
  force_encoder_cfg:
    model_name: causalconv
    feature_dim: 384
    frozen: False
    pretrained: False
    use_group_norm: False
    share_force_model: False


model:
  _target_: diffusion_policy.model.residual.transformer.Transformer
  d: 768
  h: 8
  d_ff: 2048
  a: 15
  num_layers: 2
  dropout: 0.1
  horizon: ${task.sparse_obs_base_horizon}

dataloader:
  batch_size: 128 # debug 128
  num_workers: 32 # debug 32
  shuffle: True
  pin_memory: True
  persistent_workers: True # debug: True

val_dataloader:
  batch_size: 128 # debug 128
  num_workers: 32 # debug 32
  shuffle: False
  pin_memory: True
  persistent_workers: True # debug: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 3.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 1000 # debug 2000
  num_epochs: 200 # debug 80
  first_time_lr_warmup_steps: 2000 # debug 2000
  first_time_num_epochs: 200 # epochs to train for the first time
  log_gradient_norm: False

  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 10
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  # number of samples to use for training
  num_samples: 12800


logging:
  project: online-residual
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}_${name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 20
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: ${output_dir}/${now:%Y.%m.%d}_${now:%H.%M.%S}_${task_name}_${name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}_${name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ${output_dir}/${now:%Y.%m.%d}_${now:%H.%M.%S}_${task_name}_${name}
  sweep:
    dir: ${output_dir}/${now:%Y.%m.%d}_${now:%H.%M.%S}_${task_name}_${name}
    subdir: ${hydra.job.num}
