defaults:
  - _self_
  # - task: online_correction_single_arm.yaml
  - task: online_correction_single_arm_no_base_action.yaml

name: online_residual_mlp

output_dir: ${oc.env:PYRITE_CHECKPOINT_FOLDERS}
_target_: diffusion_policy.workspace.train_online_residual_mlp_workspace.TrainOnlineResidualMLPWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.22_04.27.42_stow_new_blade_stow/checkpoints/latest.ckpt"
# finetune 50
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.26_16.52.38_stow_new_blade_dagger1_finetune_50/checkpoints/latest.ckpt"
# finetune 50 no encoder
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.27_00.55.22_stow_new_blade_dagger1_finetune_50_no_encoder/checkpoints/latest.ckpt"
# finetune 50 correction data, no encoder
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.27_11.24.31_stow_new_blade_correction_finetune_50_no_encoder/checkpoints/latest.ckpt"
# dagger with correction
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.27_20.54.03_stow_new_blade_stow/checkpoints/latest.ckpt"
# retrain from scratch, dagger data
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.28_02.15.15_stow_new_blade_stow/checkpoints/latest.ckpt"
# Dagger with take over data
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.29_03.26.00_stow_new_blade_stow/checkpoints/latest.ckpt"
# finetune with take over data
# retrain from scratch, 50 offline data
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.30_01.14.38_stow_new_blade_correction_stow/checkpoints/latest.ckpt"

# finetune with correction, more sampling
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.29_22.05.27_stow_new_blade_correction_finetune_50_no_encoder_more_sampling/checkpoints/latest.ckpt"
# finetune with correction, no sampling (new)
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.29_22.12.10_stow_new_blade_correction_finetune_50_no_encoder_no_sampling/checkpoints/latest.ckpt"
# finetune 50new no encoder
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.30_01.06.58_stow_new_blade_correction_finetune_offline_50_no_encoder/checkpoints/latest.ckpt"
# finetune with correction, sample more both before and after correction
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.30_03.00.29_stow_new_blade_correction_finetune_correction_50_no_encoder_denser_sample_before_and_after/checkpoints/latest.ckpt"

# dagger finetune batch5
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.22_04.27.42_stow_new_blade_stow/2025.04.29_17.37.27_batch5_finetune/checkpoints/latest.ckpt"
# dagger finetune batch10
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.04.22_04.27.42_stow_new_blade_stow/2025.04.30_14.48.07_batch10_finetune/checkpoints/latest.ckpt"

### ------------------------------- Belt assembly ------------------------------- ###
# belt assembly base policy ckpt
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.02_00.02.43_stow_belt_assembly_stow/checkpoints/latest.ckpt"
# finetune with correction
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.05_22.15.51_belt_assembly_finetune_finetune/checkpoints/latest.ckpt"
# retrain from scratch with base + correction only data
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.05_22.38.49_belt_assembly_finetune_stow/checkpoints/latest.ckpt"

# retrain from scratch with base + correction only data
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.05_22.38.49_belt_assembly_finetune_stow/checkpoints/latest.ckpt"
# retrain w takeover 50
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.06_08.05.53_belt_assembly_retrain_takeover_stow/checkpoints/latest.ckpt"
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.06_06.47.52_belt_assembly_finetune_takeover_finetune/checkpoints/latest.ckpt"

# retrain w offline 50
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.06_19.03.06_belt_assembly_retrain_offline_stow/checkpoints/latest.ckpt"
# finetune w offline 50
# base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.05.06_20.42.52_belt_assembly_finetune_offline_finetune/checkpoints/latest.ckpt"

### ------------------------------- Belt angled -------------------------------- ###
base_policy_ckpt: "${oc.env:PYRITE_CHECKPOINT_FOLDERS}/2025.06.17_07.26.20_belt_angled_150_dp/checkpoints/latest.ckpt"

obs_encoder:    
  _target_: diffusion_policy.model.vision.timm_obs_encoder_with_force.TimmObsEncoderWithForce
  shape_meta: ${shape_meta}
  fuse_mode: modality-attention
  reduce_pretrained_lr: True

  ##### from scratch #####
  # model_name: 'vit_base_patch16_224'
  # model_name: 'resnet34'
  # model_name: 'vit_tiny_patch16_224'
  # model_name: 'efficientnet_b0'
  # model_name: 'efficientnet_b3'
  # pretrained: False
  # frozen: False

  vision_encoder_cfg:   # TODO: load this from base policy
    ##### from scratch #####
    # model_name: 'resnet34.a1_in1k'
    model_name: 'vit_base_patch32_clip_224.openai'
    # model_name: 'convnext_base.clip_laion2b_augreg_ft_in12k'
    pretrained: True
    frozen: True
    global_pool: ''

    # 'avg' or 'max' or 'soft_attention' or 'spatial_embedding' or 'transformer' or 'attention_pool_2d'
    feature_aggregation: 'attention_pool_2d'
    # feature_aggregation: null
    position_encoding: null

    # it only works for resnet. 32 (7x7) or 16 (14x14)
    downsample_ratio: 32

    transforms:
      - type: RandomCrop
        ratio: 0.95
      # RandomRotation is not compatible with BF16
      # - _target_: torchvision.transforms.RandomRotation
      #   degrees:
      #     - -5.0
      #     - 5.0
      #   expand: false
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.4
        saturation: 0.5
        hue: 0.08
      # - _target_: torchvision.transforms.RandomPerspective
      #   distortion_scale: 0.5
      #   p: 1.0
      # - _target_: torchvision.transforms.ElasticTransform
      #   alpha: 50.0
      #   sigma: 5.0
      # - _target_: torchvision.transforms.RandomPerspective
      #   distortion_scale: 0.5
      #   p: 1.0
      # - _target_: torchvision.transforms.ElasticTransform
      #   alpha: 50.0
      #   sigma: 5.0
      # - _target_: torchvision.transforms.RandomCrop
      #   size: 192

    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True
  
  force_encoder_cfg:
    model_name: causalconv
    feature_dim: 384
    frozen: False
    pretrained: False
    use_group_norm: False
    share_force_model: False


model:
  _target_: diffusion_policy.model.residual.mlp.MLPResidual
  action_dim: 15
  action_horizon: ${task.sparse_action_horizon}
  hidden_dims: [256, 256, 256]
  dropout: 0.1

dataloader:
  batch_size: 128 # debug 128
  num_workers: 32 # debug 32
  shuffle: True
  pin_memory: True
  persistent_workers: True # debug: True

val_dataloader:
  batch_size: 128 # debug 128
  num_workers: 32 # debug 32
  shuffle: False
  pin_memory: True
  persistent_workers: True # debug: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 3.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 2000 # debug 2000
  num_epochs: 31 # debug 80
  first_time_lr_warmup_steps: 2000 # debug 2000
  first_time_num_epochs: 201 # epochs to train for the first time
  log_gradient_norm: False

  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 10
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  # number of samples to use for training
  num_samples: 1000000000 # 12800

logging:
  project: online-residual
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}_${name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 20
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: ${output_dir}/${now:%Y.%m.%d}_${now:%H.%M.%S}_${task_name}_${name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}_${name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ${output_dir}/${now:%Y.%m.%d}_${now:%H.%M.%S}_${task_name}_${name}
  sweep:
    dir: ${output_dir}/${now:%Y.%m.%d}_${now:%H.%M.%S}_${task_name}_${name}
    subdir: ${hydra.job.num}
